// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAuY1BASHEUT91Kx2-6osNDbU6FDupnTg',
    appId: '1:439520952864:web:a8b1cb9af7b2b8a042f245',
    messagingSenderId: '439520952864',
    projectId: 'auth-23426',
    authDomain: 'auth-23426.firebaseapp.com',
    storageBucket: 'auth-23426.appspot.com',
    measurementId: 'G-3ZQEBRL0WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmrnSgX3vcLDN4NilVZp0TtR7cVay0Bwo',
    appId: '1:439520952864:android:16684cc584fe731942f245',
    messagingSenderId: '439520952864',
    projectId: 'auth-23426',
    storageBucket: 'auth-23426.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3IdCEcFhc80ha4jZzA06gSFAxRfvcmOQ',
    appId: '1:439520952864:ios:74fe444dbdadfa7642f245',
    messagingSenderId: '439520952864',
    projectId: 'auth-23426',
    storageBucket: 'auth-23426.appspot.com',
    androidClientId: '439520952864-vdsh839hhg8hr6j5ua7muov6m2s5mpf0.apps.googleusercontent.com',
    iosClientId: '439520952864-aon83abov46jo4lmgu4a0jg54stihkm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dairyDaze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3IdCEcFhc80ha4jZzA06gSFAxRfvcmOQ',
    appId: '1:439520952864:ios:74fe444dbdadfa7642f245',
    messagingSenderId: '439520952864',
    projectId: 'auth-23426',
    storageBucket: 'auth-23426.appspot.com',
    androidClientId: '439520952864-vdsh839hhg8hr6j5ua7muov6m2s5mpf0.apps.googleusercontent.com',
    iosClientId: '439520952864-aon83abov46jo4lmgu4a0jg54stihkm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dairyDaze',
  );
}
